version: '3'
services:

  db:
    build: ./db
    image: greynir/db
    container_name: greynir_db
    environment:
      - POSTGRES_USER=reynir
      - POSTGRES_PASSWORD=reynir

  web:
    build: ./web
    image: greynir/web
    container_name: greynir_web
    ports: 
      - "5050:5000"
    depends_on: 
      - db
    restart: always

