version: '2'
services:
  web:
    image: busla/greynir_web
    ports:
    - "5000:5000"
    links: postgres
  
  postgres:
    image: busla/greynir_db
    links: data
  
  data:
    image: busla/greynir_data
