version: '2'
services:  

  postgres:
    build: ./greynir-docker-db
    image: busla/greynir_db
    container_name: greynir_db
    ports: 
    - 0.0.0.0:5432:5432

  web:
    build: ./greynir-docker-web
    container_name: greynir_web
    image: busla/greynir_web
    ports: 
    - 0.0.0.0:5000:5000
    links: 
    - postgres
    depends_on: 
    - postgres
    command: /bin/bash -c "pypy3 scraper.py --init;  pypy3 main.py"
