version: '2'
services:  

  web:
    build: ./web
    image: greynir/web
    container_name: greynir_web
    ports: 
      - 0.0.0.0:5000:5000
    links: 
      - postgres
    depends_on: 
      - postgres
    restart: always

  postgres:
    build: ./db
    image: greynir/db
    container_name: greynir_db
    ports: 
      - 0.0.0.0:5432:5432


